#!/bin/bash -eu

if [[ ( ( ! -x /root/bin/tesla_api.py) || ( ! -s /mutable/cache.json ) ) && ( -z "${TESLAFI_API_TOKEN:+x}" ) ]]
then
  log "Not keeping car awake."
  exit
fi

case "${TESLA_SENTRY_CHECK:-off}" in
  on)
    is_sentry_check=$(/root/bin/tesla_api.py is_sentry_check | tr '[:upper:]' '[:lower:]')
    if [ "0" = "${is_sentry_check}" ]
    then
      log "Sentry was triggered by an event."
    fi
    ;;
  off)
    log "Sentry check is disactive."
    ;;
  *)
    log "Unknown TESLA_SENTRY_CHECK: ${TESLA_SENTRY_CHECK}."
    ;;
esac
