#!/bin/bash -eu

if [[ ( ( ! -x /root/bin/tesla_api.py) || ( ! -s /mutable/cache.json ) ) && ( -z "${TESLAFI_API_TOKEN:+x}" ) ]]
then
  log "No api Token."
  exit
fi

get_sentry_check=$(/root/bin/tesla_api.py get_sentry_check | tr '[:upper:]' '[:lower:]')
if [ "0" = "${get_sentry_check}" ]
then
  log "Sentry was triggered by an event."
fi
